In [1]:
import numpy as np
import numpy.linalg
import scipy.linalg
import scipy.sparse as sparse
import scipy.sparse.linalg as linalg
import math
import matplotlib.pyplot as plt

In [2]:
import xylo
import xylo.types as t
import xylo.woods
import xylo.cut
import xylo.receptance as r
import xylo.sweep

In [19]:
E = 30e6
h = 0.01
poisson = 0.3
L = 1
wid = 0.1
rho = 800
num_elements = 10

bar = t.BarProps(width = wid, depth = h, length = L, elements = num_elements, min_depth = h)
wood = t.Wood.make_E_nu(rho = rho, E = E, nu = poisson)
cut = t.CutCubic(cubic = 0, square = 0, offset = 0)
sec = xylo.cut.cubic(bar, cut)


In [20]:
wood, bar, sec

(Wood(rho=800, E=30000000.0, G=11538461.538461538, nu=0.3),
 BarProps(width=0.1, depth=0.01, length=1, elements=10, min_depth=0.01),
 Sections(xmids=Array([-0.45, -0.35, -0.25, -0.15, -0.05,  0.05,  0.15,  0.25,  0.35,
         0.45], dtype=float64), depths=Array([0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01],      dtype=float64), length_per_element=0.1))

In [21]:
r.receptance(wood, bar, sec, 10)

Array([[0.04530125, 0.40176675],
       [0.40176675, 2.58929548]], dtype=float64)

In [23]:
r.receptance(wood, bar, sec, 20)

Array([[-0.0246033 , -0.03472766],
       [-0.03472766,  0.46435436]], dtype=float64)

In [24]:
r.receptance(wood, bar, sec, 30)

Array([[0.0074133 , 0.12907456],
       [0.12907456, 1.49274846]], dtype=float64)

In [25]:
r.receptance(wood, bar, sec, 50)

Array([[-0.00453933,  0.00182029],
       [ 0.00182029,  0.43975323]], dtype=float64)

In [26]:
r.receptance(wood, bar, sec, 80)

Array([[-0.00389741, -0.0186356 ],
       [-0.0186356 ,  0.11101509]], dtype=float64)

In [27]:
r.receptance(wood, bar, sec, 130)

Array([[-0.0016425 , -0.00781019],
       [-0.00781019,  0.14265244]], dtype=float64)