In [1]:
# Suits 2001
# Recreating some data from Suits 2001 paper: "Basic physics of xylophone and marimba bars"

In [2]:
import jax.numpy as jnp
import math
import matplotlib.pyplot as plt

In [3]:
import xylo
import xylo.types as t
import xylo.woods
import xylo.cut
import xylo.receptance as r
import xylo.sweep

In [8]:
no_cut = t.CutCubic(cubic = 0, square = 0, offset = 0)

oak = t.Wood.make_E_G(rho = 760, E = 14.7e9, G = 1.47e9)


In [11]:
def sweep_no_cut(bar: t.BarProps, mat: t.Wood = oak, sweep = t.FrequencySweep(start_freq = 10, stop_freq = 20000, num_freq = 200, num_harmonics = 5, bisect_iters = 10)):
    sec = xylo.cut.cubic(bar, no_cut)
    swp = xylo.sweep.sweep(mat, bar, sec, sweep)
    return swp.harmonics

In [12]:
# Table 1, row 1
oak1 = t.Wood.make_E_G(rho = 760, E = 14.7e9, G = 1.47e9)
oak1_bar = t.BarProps(width = 0.032, depth = 0.014, length = 0.214, elements = 400, min_depth = 0.014)
sweep_no_cut(oak1_bar, oak1)
# Expect first fundamental ~1340

Array([ 1336.36781733,  3432.56803807,  6148.59948068,  9193.74116303,
       12396.18594884], dtype=float64)

In [13]:
# Table 1, row 2
sweep_no_cut(t.BarProps(width = 0.032, depth = 0.014, length = 0.329, elements = 500, min_depth = 0.014), t.Wood.make_E_G(rho = 760, E = 13.6e9, G = 1.36e9))
# Expect first fundamental ~550

Array([ 554.27655233, 1478.9225941 , 2769.76832847, 4330.95385095,
       6081.47359799], dtype=float64)

In [14]:
# Table 1, row 3
sweep_no_cut(t.BarProps(width = 0.032, depth = 0.014, length = 0.273, elements = 500, min_depth = 0.014), t.Wood.make_E_G(rho = 680, E = 13.7e9, G = 1.37e9))
# Expect first fundamental ~850

Array([ 848.69615623, 2234.44067457, 4116.05812608, 6324.30229374,
       8733.6808192 ], dtype=float64)

In [15]:
# Table 1, row 4
sweep_no_cut(t.BarProps(width = 0.032, depth = 0.014, length = 0.243, elements = 500, min_depth = 0.014), t.Wood.make_E_G(rho = 680, E = 15.1e9, G = 1.51e9))
# Expect first fundamental ~1140

Array([ 1118.6446875 ,  2913.92475939,  5301.21638195,  8044.52868931,
       10984.77416057], dtype=float64)

In [16]:
# Table 1, row 5
sweep_no_cut(t.BarProps(width = 0.032, depth = 0.014, length = 0.222, elements = 500, min_depth = 0.014), t.Wood.make_E_G(rho = 380, E = 9.9e9, G = 0.99e9))
# Expect first fundamental ~1430

Array([ 1444.47162801,  3726.37105582,  6706.28355761, 10071.73689927,
       13629.53491738], dtype=float64)

In [17]:
# Table 1, row 6
sweep_no_cut(t.BarProps(width = 0.032, depth = 0.014, length = 0.273, elements = 500, min_depth = 0.014), t.Wood.make_E_G(rho = 400, E = 7.3e9, G = 0.73e9))
# Expect first fundamental ~810

Array([ 807.75674692, 2126.66462278, 3917.51423511, 6019.20222109,
       8312.24867179], dtype=float64)

In [22]:
# Figure 6
# Timoshenko G=E/10
def f6e10(length: float):
    bar = t.BarProps(width = 0.0305, depth = 0.0191, length = length, elements = 500, min_depth = 0.0191)
    swp = sweep_no_cut(bar, oak)
    # print(swp)
    print(swp[1] / swp[0])

# Expect range from ~2.3 to ~2.6, increasing
f6e10(0.20)
f6e10(0.25)
f6e10(0.30)
f6e10(0.35)

2.419862482347648
2.515087100190847
2.576885631884346
2.6184102943929486
